[package]
name = "oncrit"
version = "0.8.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "oncrit"
crate-type = ["cdylib"]
# path = "rust_bindings/lib.rs"

[dependencies]
pyo3 = "0.24.2"

